//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evrostroy.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class evrostroydbEntities : DbContext
    {
        public evrostroydbEntities()
            : base("name=evrostroydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ДопИнформация> ДопИнформация { get; set; }
        public virtual DbSet<ДопХарактеристики> ДопХарактеристики { get; set; }
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<Контакты> Контакты { get; set; }
        public virtual DbSet<НовостиСтатьи> НовостиСтатьи { get; set; }
        public virtual DbSet<ОснХарактеристики> ОснХарактеристики { get; set; }
        public virtual DbSet<ОтзывМагазина> ОтзывМагазина { get; set; }
        public virtual DbSet<ОтзывТовара> ОтзывТовара { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<ТоваровЗаказа> ТоваровЗаказа { get; set; }
        public virtual DbSet<Товары> Товары { get; set; }
        public virtual DbSet<Услуги> Услуги { get; set; }
        public virtual DbSet<ФотоТовара> ФотоТовара { get; set; }
    }
}
