//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evrostroy.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ДопИнформация
    {
        public int ИдДопИнформации { get; set; }
        public string Доставка { get; set; }
        public string Оплата { get; set; }
        public string Омагазине { get; set; }
    }
}
