//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evrostroy.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.ТоваровЗаказа = new HashSet<ТоваровЗаказа>();
        }
    
        public int ИдЗаказа { get; set; }
        public int ИдПользователя { get; set; }
        public int Сумма { get; set; }
        public string Статус { get; set; }
        public string СпособОплаты { get; set; }
        public string КомментарийПокупателя { get; set; }
        public bool НаличиеУслуги { get; set; }
        public System.DateTime ДатаЗаказа { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТоваровЗаказа> ТоваровЗаказа { get; set; }
    }
}
