//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evrostroy.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class НовостиСтатьи
    {
        public int ИдНовости { get; set; }
        public string Заголовок { get; set; }
        public string Аннотация { get; set; }
        public string Содержание { get; set; }
    }
}
