//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace evrostroy.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.ДопХарактеристики = new HashSet<ДопХарактеристики>();
            this.ОтзывТовара = new HashSet<ОтзывТовара>();
            this.ТоваровЗаказа = new HashSet<ТоваровЗаказа>();
            this.ФотоТовара = new HashSet<ФотоТовара>();
        }
    
        public int ИдТовара { get; set; }
        public string Название { get; set; }
        public string Производитель { get; set; }
        public string СтранаПроизводитель { get; set; }
        public string Категория { get; set; }
        public string Подкатегория1 { get; set; }
        public string Подкатегория2 { get; set; }
        public string Метка { get; set; }
        public bool Публикация { get; set; }
        public int Цена { get; set; }
        public Nullable<int> Скидка { get; set; }
        public Nullable<int> ЦенаСоСкидкой { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ДопХарактеристики> ДопХарактеристики { get; set; }
        public virtual ОснХарактеристики ОснХарактеристики { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОтзывТовара> ОтзывТовара { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТоваровЗаказа> ТоваровЗаказа { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ФотоТовара> ФотоТовара { get; set; }
    }
}
